import { CHIP_RADIUS } from '../chips/Chip.js';

export const HERO_SLOT_PADDING = 16;
export const HERO_CHIP_DIAMETER = CHIP_RADIUS.hero * 2;
export const HERO_SLOT_SIZE = HERO_CHIP_DIAMETER + HERO_SLOT_PADDING * 2;
export const BATTLE_ENEMY_SLOT_COUNT = 6;
export const BATTLE_FRIENDLY_SLOT_COUNT = 4;
export const BATTLE_ENEMY_AREA_HEIGHT = HERO_CHIP_DIAMETER * 2;
export const BATTLE_FRIENDLY_AREA_HEIGHT = HERO_SLOT_SIZE;
export const BATTLE_AREA_HEIGHT = BATTLE_ENEMY_AREA_HEIGHT + BATTLE_FRIENDLY_AREA_HEIGHT;
export const ENEMY_CHIP_DIAMETER = Object.freeze({ small: 128, medium: HERO_CHIP_DIAMETER, large: HERO_CHIP_DIAMETER * 2 });
export const LARGE_ENEMY_SLOT_SPAN = 2;
